require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'
    - 'db/migrate/**/*'
    - 'spec/factories/**/*'
  TargetRubyVersion: 3.1

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Layout/LineLength:
  Max: 120

Style/RedundantFileExtensionInRequire:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
